//! TOML output writer for DMC simulations.

use super::{OutputError, OutputWriter};
use crate::types::SimulationResult;
use simulation::state::SimulationStep;
use std::fs::{self, File};
use std::io::Write;
use std::path::Path;

/// TOML output writer.
///
/// Writes human-readable simulation results in TOML format.
pub struct TomlWriter {
    directory: String,
    prefix: String,
}

impl TomlWriter {
    /// Create a new TOML writer.
    ///
    /// # Arguments
    ///
    /// * `directory` - Output directory
    /// * `prefix` - File name prefix
    pub fn new(directory: &str, prefix: &str) -> Result<Self, OutputError> {
        fs::create_dir_all(directory)?;

        Ok(Self {
            directory: directory.to_string(),
            prefix: prefix.to_string(),
        })
    }

    /// Write human-readable TOML summary.
    fn write_toml_result(&self, result: &SimulationResult) -> Result<(), OutputError> {
        let path = Path::new(&self.directory).join(format!("{}_result.toml", self.prefix));
        let mut file = File::create(path)?;

        writeln!(file, "# DMC Simulation Result")?;
        writeln!(file, "# Generated by Diffusion-MC")?;
        writeln!(file)?;

        writeln!(file, "[simulation]")?;
        writeln!(file, "algorithm = \"{}\"", result.algorithm)?;
        writeln!(file, "system = \"{}\"", result.system)?;
        writeln!(file, "total_steps = {}", result.total_steps)?;
        writeln!(file, "equilibration_steps = {}", result.equilibration_steps)?;
        writeln!(file, "wall_time_seconds = {:.2}", result.wall_time_seconds)?;
        writeln!(file)?;

        writeln!(file, "[energy]")?;
        writeln!(file, "# Final energy estimate in Hartree")?;
        writeln!(file, "value = {:.8}", result.energy)?;
        writeln!(file, "error = {:.8}", result.energy_error)?;
        if let Some(exact) = result.exact_energy {
            writeln!(file, "reference = {:.8}", exact)?;
            let deviation = result.energy - exact;
            let percent = 100.0 * deviation.abs() / exact.abs();
            writeln!(file, "deviation = {:.8}", deviation)?;
            writeln!(file, "deviation_percent = {:.4}", percent)?;
        }
        writeln!(file)?;

        if !result.blocks.is_empty() {
            writeln!(file, "[statistics]")?;
            writeln!(file, "num_blocks = {}", result.blocks.len())?;
            let block_energies: Vec<f64> = result.blocks.iter().map(|b| b.mean_energy).collect();
            let min_e = block_energies.iter().cloned().fold(f64::INFINITY, f64::min);
            let max_e = block_energies
                .iter()
                .cloned()
                .fold(f64::NEG_INFINITY, f64::max);
            writeln!(file, "energy_min = {:.8}", min_e)?;
            writeln!(file, "energy_max = {:.8}", max_e)?;
            writeln!(file, "energy_range = {:.8}", max_e - min_e)?;
        }

        Ok(())
    }
}

impl OutputWriter for TomlWriter {
    fn write_step(&mut self, _step: &SimulationStep) -> Result<(), OutputError> {
        // TOML writer only outputs at finalization
        Ok(())
    }

    fn finalize(&mut self, result: &SimulationResult) -> Result<(), OutputError> {
        self.write_toml_result(result)
    }

    fn flush(&mut self) -> Result<(), OutputError> {
        Ok(())
    }
}
